import { SearchSettlementResponse } from '../types';

export const SearchSettlementResponseMock: SearchSettlementResponse = {
  success: true,
  data: [{
    TotalCount: 27607,
    Addresses: [{
      Present: 'м. Київ, Київська обл.',
      Warehouses: 2188,
      MainDescription: 'Київ',
      Area: 'Київська',
      Region: '',
      SettlementTypeCode: 'м.',
      Ref: 'e718a680-4b33-11e4-ab6d-005056801329',
      DeliveryCity: '8d5a980d-391c-11dd-90d9-001a92567626',
      AddressDeliveryAllowed: true,
      StreetsAvailability: true,
      ParentRegionTypes: 'область',
      ParentRegionCode: 'обл.',
      RegionTypes: '',
      RegionTypesCode: '',
    }, {
      Present: 'м. Дніпро, Дніпропетровська обл.',
      Warehouses: 263,
      MainDescription: 'Дніпро',
      Area: 'Дніпропетровська',
      Region: '',
      SettlementTypeCode: 'м.',
      Ref: 'e717110a-4b33-11e4-ab6d-005056801329',
      DeliveryCity: 'db5c88f0-391c-11dd-90d9-001a92567626',
      AddressDeliveryAllowed: true,
      StreetsAvailability: true,
      ParentRegionTypes: 'область',
      ParentRegionCode: 'обл.',
      RegionTypes: '',
      RegionTypesCode: '',
    }, {
      Present: 'м. Одеса, Одеська обл.',
      Warehouses: 219,
      MainDescription: 'Одеса',
      Area: 'Одеська',
      Region: '',
      SettlementTypeCode: 'м.',
      Ref: 'e71c2a15-4b33-11e4-ab6d-005056801329',
      DeliveryCity: 'db5c88d0-391c-11dd-90d9-001a92567626',
      AddressDeliveryAllowed: true,
      StreetsAvailability: true,
      ParentRegionTypes: 'область',
      ParentRegionCode: 'обл.',
      RegionTypes: '',
      RegionTypesCode: '',
    }, {
      Present: 'м. Харків, Харківська обл.',
      Warehouses: 196,
      MainDescription: 'Харків',
      Area: 'Харківська',
      Region: '',
      SettlementTypeCode: 'м.',
      Ref: 'e71f8842-4b33-11e4-ab6d-005056801329',
      DeliveryCity: 'db5c88e0-391c-11dd-90d9-001a92567626',
      AddressDeliveryAllowed: true,
      StreetsAvailability: true,
      ParentRegionTypes: 'область',
      ParentRegionCode: 'обл.',
      RegionTypes: '',
      RegionTypesCode: '',
    }, {
      Present: 'м. Львів, Львівська обл.',
      Warehouses: 151,
      MainDescription: 'Львів',
      Area: 'Львівська',
      Region: '',
      SettlementTypeCode: 'м.',
      Ref: 'e71abb60-4b33-11e4-ab6d-005056801329',
      DeliveryCity: 'db5c88f5-391c-11dd-90d9-001a92567626',
      AddressDeliveryAllowed: true,
      StreetsAvailability: true,
      ParentRegionTypes: 'область',
      ParentRegionCode: 'обл.',
      RegionTypes: '',
      RegionTypesCode: '',
    }],
  }],
  errors: [],
  warnings: [],
  info: [],
  messageCodes: [],
  errorCodes: [],
  warningCodes: [],
  infoCodes: [],
};
